# Generated by Django 5.1.7 on 2025-03-25 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("endereco", models.TextField(verbose_name="Endereço")),
                ("fonte", models.CharField(max_length=255, verbose_name="Fonte")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("bloqueado", "Bloqueado"),
                        ],
                        default="ativo",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Notas e pontos importantes",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nome", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do produto"),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, verbose_name="Descrição do produto"
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Preço do produto (R$)",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Produto ativo"),
                ),
                (
                    "data_criacao",
                    models.DateField(auto_now_add=True, verbose_name="Data de criação"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("plantas", "Plantas"),
                            ("vasos", "Vasos"),
                            ("flores", "Flores"),
                            ("buquê", "Buquê de Flores"),
                            ("arranjo", "Arranjo de Flores"),
                            ("cesta", "Cesta de Presente"),
                        ],
                        max_length=17,
                        verbose_name="Categoria do produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("endereco", models.TextField(verbose_name="Endereço")),
                ("fonte", models.CharField(max_length=255, verbose_name="Fonte")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("em_progresso", "Em Progresso"),
                            ("qualificado", "Qualificado"),
                            ("desqualificado", "Desqualificado"),
                            ("fechado", "Fechado"),
                        ],
                        default="ativo",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Notas e pontos importantes",
                    ),
                ),
                (
                    "produto_interesse",
                    models.CharField(
                        max_length=255, verbose_name="Produtos ou serviços de interesse"
                    ),
                ),
                (
                    "data_conversao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de conversão"
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantia",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Quantidade em estoque"
                    ),
                ),
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoque",
                        to="crm.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_processamento", "Em Processamento"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="em_processamento",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_venda",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da venda"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(max_length=50, verbose_name="Forma de pagamento"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendas",
                        to="crm.cliente",
                    ),
                ),
                (
                    "produtos",
                    models.ManyToManyField(related_name="vendas", to="crm.produto"),
                ),
            ],
        ),
    ]
