# Generated by Django 5.1.7 on 2025-03-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="notas",
            field=models.TextField(
                blank=True, default="", verbose_name="Notas e pontos importantes"
            ),
        ),
    ]
