# Generated by Django 5.1.7 on 2025-03-21 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["nome"],
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
            },
        ),
        migrations.AlterField(
            model_name="lead",
            name="responsavel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade comprada"),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Preço unitário"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_processamento", "Em Processamento"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="em_processamento",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_venda",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da venda"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(max_length=50, verbose_name="Forma de pagamento"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendas",
                        to="crm.cliente",
                    ),
                ),
                (
                    "produtos",
                    models.ManyToManyField(through="crm.ItemVenda", to="crm.produto"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemvenda",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="crm.venda",
            ),
        ),
    ]
